### ISSUE TITLE
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'

### ISSUE THREAD

**Issue by arthurlutz** [crisbal/album-splitter#31]
```
Traceback (most recent call last):
  File "split.py", line 14, in <module>
    from split_init import METADATA_PROVIDERS, ydl_opts
  File "/home/arthur/local/album-splitter/split_init.py", line 11, in <module>
    METADATA_PROVIDERS.append(__import__("MetaDataProviders." + provider[:-3], fromlist=[""]))
  File "/home/arthur/local/album-splitter/MetaDataProviders/Wikipedia.py", line 6, in <module>
    from bs4 import BeautifulSoup
  File "/home/arthur/.virtualenvs/album-splitter/lib/python3.8/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/home/arthur/.virtualenvs/album-splitter/lib/python3.8/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/home/arthur/.virtualenvs/album-splitter/lib/python3.8/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```

```
pip list
Package        Version     
-------------- ------------
appdirs        1.4.3       
beautifulsoup4 4.4.0       
CacheControl   0.12.6      
certifi        2019.11.28  
chardet        3.0.4       
colorama       0.4.3       
contextlib2    0.6.0       
distlib        0.3.0       
distro         1.4.0       
html5lib       1.0.1       
idna           2.8         
ipaddr         2.2.0       
lockfile       0.12.2      
msgpack        0.6.2       
mutagen        1.31        
packaging      20.3        
pep517         0.8.2       
pip            20.0.2      
pkg-resources  0.0.0       
progress       1.5         
pydub          0.14.2      
pyparsing      2.4.6       
pytoml         0.1.21      
requests       2.22.0      
retrying       1.3.3       
setuptools     44.0.0      
six            1.14.0      
urllib3        1.25.8      
urlparse3      1.0.3       
webencodings   0.5.1       
wheel          0.34.2      
youtube-dl     2020.11.21.1
```

**Comment by crisbal** [comment]
Not valid anymore, closing.
