### ISSUE TITLE
keeps giving me this error message and wont download the video (i am on windows wsl)

### ISSUE THREAD

**Issue by lperez509** [crisbal/album-splitter#38]
Parsing tracks.txt
Tracks file parsed
Downloading video from YouTube
Traceback (most recent call last):
  File "split.py", line 177, in <module>
    ydl.download(['http://www.youtube.com/watch?v=' + video_id])
  File "C:\Users\09515\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1919, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Users\09515\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 762, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\09515\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\common.py", line 433, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\09515\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1506, in _real_extract
    if 'token' not in video_info:
TypeError: argument of type 'NoneType' is not iterable
'ab_channel' is not recognized as an internal or external command,
operable program or batch file.

**Comment by crisbal** [comment]
It is possible that you are using an outdated version of youtube-dl. I would suggest the following:

```bash
pip uninstall youtube-dl
pip install youtube-dl
````

And then trying again

**Comment by crisbal** [comment]
Hello!

Good news, I had some time today and decided to rework/redo the whole project. 
It should be able to handle your case of big files now, hopefully.

Please give it a try and see if it works for you too. You will need to re-download the project and start from scratch

**Comment by lperez509** [comment]
thank you i will test it

**Comment by lperez509** [comment]
it works now thank you!!

**Comment by crisbal** [comment]
Amazing! Glad to help
