### ISSUE TITLE
Error while splitting

### ISSUE THREAD

**Issue by melaww** [crisbal/album-splitter#43]
Hello. I get this error, what have I done wrong?
Apologies because I am not very familiar with programming. Willing to learn tho.
Thank you.

```
Splitting into files... (this could take a while)
Traceback (most recent call last):
  File "C:\Programme2\Miniconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Programme2\Miniconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Programme2\album-splitter-master\album_splitter\__main__.py", line 171, in <module>
    output_files = split_file(input_file, tracks, outfolder, output_format=str(input_file).split(".")[-1])
  File "C:\Programme2\album-splitter-master\album_splitter\split_file.py", line 11, in split_file
    inputs={input_file: '-show_entries format=duration -v quiet -of csv="p=0"'}
  File "C:\Programme2\album-splitter-master\venv\lib\site-packages\ffmpy.py", line 129, in __init__
    executable=executable, global_options=global_options, inputs=inputs
  File "C:\Programme2\album-splitter-master\venv\lib\site-packages\ffmpy.py", line 57, in __init__
    self.cmd = subprocess.list2cmdline(self._cmd)
  File "C:\Programme2\Miniconda\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

```

**Comment by crisbal** [comment]
Hello, I did some work to attempt to fix this issue. Could you try updating the code you have locally (by re-downloading the project and following the readme, or via git) and try again? 
Sorry it took a while

**Comment by jaggedquilt** [comment]
Hey, I ran into this same issue today with the latest version. After some googling, it looks like an issue with Path (at least on Windows).

I was able to get it working by changing the call to split_file in __main__ to wrap the first parameter in str( )
`    output_files = split_file(str(input_file), tracks, outfolder, output_format=str(input_file).split(".")[-1])`

Not sure if that will cause any other issues, but at least in my case it seemed to fix it.
