### ISSUE TITLE
-to value smaller than -ss; aborting.

### ISSUE THREAD

**Issue by queer-bird** [crisbal/album-splitter#58]
I'm not sure what this error means.
`-to value smaller than -ss; aborting.`
I assumed it had something to do with the file being shorting than the timestamps provied but this doesn't seem to be the case. The file is exactly 01:01:02 in length and the last time stamp is at 1:00:18

Any idea what is going on here?

The full output is as follows:
```
➜ split Album.mp3
Reading tracks file
Found the following tracks: 
        song 1  - 0:00:00
        song 2  - 0:02:03
        song 3  - 0:03:23
        song 4  - 0:04:27
        song 5  - 0:08:24
        song 6  - 0:12:26
        song 7  - 0:15:07
        song 8  - 0:19:56
        song 9  - 0:23:58
        song 10  - 0:25:48
        song 12  - 0:27:07
        song 13  - 0:29:21
        song 14  - 0:30:52
        song 15  - 0:31:50
        song 16  - 0:33:13
        song 17  - 0:24:43
        song 18  - 0:36:11
        song 19  - 0:36:46
        song 20  - 0:40:58
        song 21  - 0:45:49
        song 22  - 0:51:23
        song 23  - 0:55:46
        song 24  - 1:00:18
Splitting into files... (this could take a while)
-to value smaller than -ss; aborting.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/cmde/py/lib/python3.11/site-packages/album_splitter/__main__.py", line 200, in <module>
    main()
  File "/home/cmde/py/lib/python3.11/site-packages/album_splitter/__main__.py", line 188, in main
    output_files = split_file(
                   ^^^^^^^^^^^
  File "/home/cmde/py/lib/python3.11/site-packages/album_splitter/split_file.py", line 37, in split_file
    raise Exception(
Exception: Something went wrong with the splitting procedure. See the error above.

```

**Comment by queer-bird** [comment]
Oh nevermind, I see one of the tracks is out of order. Oy.
